name: Build et Release App

on:
  push:
    tags:
      - 'v*'  # Se déclenche quand vous créez un tag v1.0.0, v1.1.0, etc.
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false  # Continue même si un OS échoue
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build React app
      run: npm run build
    
    - name: Build Electron app
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.os }}
        path: dist/
        if-no-files-found: warn
